version: '2.5'
services:
  postgres:
    image: postgres:latest
    environment:
      - "POSTGRES_USER=postgres"
      - "POSTGRES_PASSWORD=postgres"
      - "POSTGRES_DATABASE=postgres"
    ports:
      - 5432
    volumes: 
      - ./postgres-data:/var/lib/postgresql/data
      - ./db/postgres.sql:/docker-entrypoint-initdb.d/postgres.sql
    healthcheck:
      test: pg_isready -U postgres
  app:
    build: ./app
    ports:
      - 4000:4000
    depends_on:
      postgres:
         condition: service_healthy
  api:
    build: ./api
    ports:
      - 5000:5000
    depends_on:
      postgres:
         condition: service_healthy